/**
 * The database schema.
 *
 * Everything above `savedAnalysis` is generated by `npx @better-auth/cli
 * generate` from `lib/auth.ts` — regenerate it rather than editing it by hand,
 * or the next upgrade will silently disagree with the library about what a
 * session row looks like.
 *
 * Note what is *not* here: the 2,830 block groups. That table is written by
 * the Python pipeline, read once per server instance and held in memory, and
 * has no ORM over it at all — the SQL that touches geometry is meant to be
 * read. This schema is only for the rows that belong to a person.
 */

import { relations, sql } from "drizzle-orm";
import { check, index, pgTable, text, timestamp, boolean } from "drizzle-orm/pg-core";

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").default(false).notNull(),
  image: text("image"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

export const session = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expires_at").notNull(),
    token: text("token").notNull().unique(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (table) => [index("session_userId_idx").on(table.userId)],
);

export const account = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at"),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
    scope: text("scope"),
    password: text("password"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [index("account_userId_idx").on(table.userId)],
);

export const verification = pgTable(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [index("verification_identifier_idx").on(table.identifier)],
);

export const userRelations = relations(user, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, {
    fields: [session.userId],
    references: [user.id],
  }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, {
    fields: [account.userId],
    references: [user.id],
  }),
}));

/**
 * An analysis someone kept.
 *
 * It stores the *question*, never the result. Re-running is cheap — a preset
 * costs nothing and a cached question costs nothing — while a stored result
 * would be a copy of the dataset that silently goes stale the next time the
 * pipeline runs, and would answer with last year's floodplain while claiming
 * to be current.
 *
 * The slug is the primary key because it is the thing the outside world holds:
 * it is in every shared URL, so a separate surrogate id would exist only to be
 * looked up by it.
 */
export const savedAnalysis = pgTable(
  "saved_analysis",
  {
    /** Short, URL-safe, and the identity of the row. */
    slug: text("slug").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    /** What the person called it. Defaults to the plan's own title. */
    title: text("title").notNull(),
    /** Exactly one of these is set; the check constraint below enforces it. */
    presetId: text("preset_id"),
    question: text("question"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => [
    // The list page reads one user's rows, newest first. Without this it is a
    // sequential scan that gets slower as other people save things.
    index("saved_analysis_user_created_idx").on(table.userId, table.createdAt.desc()),
    // A row with neither a preset nor a question cannot be re-run, and a row
    // with both is ambiguous about which one wins. The database refuses both,
    // so no code path can create one by forgetting.
    check(
      "saved_analysis_one_source",
      sql`(${table.presetId} IS NULL) <> (${table.question} IS NULL)`,
    ),
  ],
);

export const savedAnalysisRelations = relations(savedAnalysis, ({ one }) => ({
  user: one(user, { fields: [savedAnalysis.userId], references: [user.id] }),
}));
